### ISSUE TITLE
Make Price command more reliable

### ISSUE THREAD

**Issue by Reisbrot** [kyranet/Skyra-i18n#9]
Since, if your API is down, the Command to convert a Currencie doesnt work, you should safe the last known courses and their Timestamps.
Also, reli on more than one API (if there is any), so if ones down nobody cares.
And, if ure super motivated, idk ask your bot if the values are different between various apis, so that guys speculating the price and not actualy knowing them doesnt fake your price. Im not an Stock expert you know, I guess that doesnt work like that, so forget about it luul

**Comment by kyranet** [comment]
Already fixed.

**Comment by Reisbrot** [comment]
Neat.
